---

- name: install keystone pkgs
  apt: >
    name={{ item }}
    state=installed
  with_items: keystone_pkgs

- name: keystone stopped
  service: >
    name=keystone
    state=stopped
    enabled=no

- name: invalid automatic execution
  shell: echo "manual" > /etc/init/keystone.override

- name: setting keystone config
  template: >
    src=keystone.conf.j2
    dest=/etc/keystone/keystone.conf
    owner=keystone
    group=keystone
    mode=0644
    backup=yes
  notify: restart apache2

- name: setting apache2 config
  template: >
    src=apache2.conf.j2
    dest=/etc/apache2/apache2.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: restart apache2

- name: setting wsgi config
  template: >
    src=wsgi-keystone.conf.j2
    dest=/etc/apache2/sites-available/wsgi-keystone.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: restart apache2

- name: 
  file: >
    src=/etc/apache2/sites-available/wsgi-keystone.conf
    dest=/etc/apache2/sites-enabled/wsgi-keystone.conf
    state=link
  notify: restart apache2



- name: keystone setup1
  shell: /usr/bin/keystone-manage pki_setup --keystone-user keystone --keystone-group keystone
  become: yes
  become_user: keystone

- name: keystone setup2
  shell: /usr/bin/keystone-manage db_sync
  become: yes
  become_user: keystone


- name: keystone pki file authority change
  file: >
    path=/etc/keystone/ssl
    owner=keystone
    group=keystone
    mode=770

- name: delete sqlite database
  file: >
    dest=/var/lib/keystone/keystone.db
    state=absent

