- name: restart nova control
  service: name={{ item }} state=restarted
  with_items:
    - "nova-api"
    - "nova-cert"
    - "nova-conductor"
    - "nova-consoleauth"
    - "nova-spiceproxy"
    - "nova-scheduler"

