- name: restart neutron network
  service: name={{ item }} state=restarted
  with_items:
    - "neutron-l3-agent"
    - "neutron-metadata-agent"
    - "neutron-lbaas-agent"
    - "neutron-plugin-openvswitch-agent"
    - "neutron-dhcp-agent"
    - "neutron-metering-agent"

- name: reflect setting of kernel
  shell: sysctl -p
