---

- name: create databases
  mysql_db: >
    name=ceilometer
    state=present
    encoding=utf8

- name: database user create
  mysql_user: >
    name=ceilometer
    host={{ item }}
    password={{ mysql_ceilometer_password }}
    priv=ceilometer.*:ALL
  with_items: 
    - '%'
    - 'localhost'

