---

- name: database user create
  shell: >
    mongo --host "{{ controller_int_ip }}" --eval '
      db = db.getSiblingDB("ceilometer");
      db.createUser({user: "ceilometer",
      pwd: "{{ mongodb_ceilometer_password }}",
      roles: [ "readWrite", "dbAdmin" ]})'
  ignore_errors: True


#  mongodb_user: >
#    database=ceilometer
#    name=ceilometer
#    password={{ mongodb_ceilometer_password }}
#    roles='readWrite,dbAdmin'
#    state=present

