---

- command: ovs-vsctl show | grep br-int
  register: br_int_exist
  ignore_errors: True
  failed_when: br_int_exist.rc not in [0, 1]

- name: setting openswitch for br-int
  shell: >
    ovs-vsctl add-br br-int
  ignore_errors: True
  when: network_type == "neutron-flat" and br_int_exist.rc == 1

- name: install neutron
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
    - "neutron-l3-agent"
    - "neutron-dhcp-agent"
    - "neutron-metadata-agent"
    - "neutron-lbaas-agent"
    - "neutron-plugin-openvswitch-agent"
  when: network_type == "neutron-flat"

- name: setting kernel parameta
  template: >
    src=sysctl.conf.j2
    dest=/etc/sysctl.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify:
    - reflect setting of kernel
  when: network_type == "neutron-flat"

- command: grep FOR_CHK /etc/neutron/neutron.conf
  register: chk_neutron_conf
  ignore_errors: True
  failed_when: chk_neutron_conf.rc not in [0, 1]

- name: setting neutron config
  template: >
    src=neutron.conf.j2
    dest=/etc/neutron/neutron.conf
    owner=neutron
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-flat" and chk_neutron_conf.rc == 1

#- name: check nova_tenant_id
#  shell: . /home/stack/admin-openrc.sh ; keystone tenant-list | grep service | awk '{print $2}'
#  register: nova_tenant_id
#  ignore_errors: True
#  when: network_type == "neutron-flat"

#- name: setting neutron config nova_tenant_id
#  lineinfile:
#    dest=/etc/neutron/neutron.conf
#    state=present
#    regexp='xxxx'
#    line="nova_admin_tenant_id = {{ item }}"
#    backup=yes
#  with_items: nova_tenant_id.stdout_lines
#  when: network_type == "neutron-flat"

- name: setting neutron l3_agent config
  template: >
    src=l3_agent.ini.j2
    dest=/etc/neutron/l3_agent.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-flat"

- name: setting neutron dhcp_agent config
  template: >
    src=dhcp_agent.ini.j2
    dest=/etc/neutron/dhcp_agent.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-flat"

- name: setting neutron metadata_agent config
  template: >
    src=metadata_agent.ini.j2
    dest=/etc/neutron/metadata_agent.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-flat"

- name: setting neutron lbaas_agent config
  template: >
    src=lbaas_agent.ini.j2
    dest=/etc/neutron/lbaas_agent.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-flat"

- name: setting neutron ml2 config
  template: >
    src=ml2_conf.ini.j2
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-flat"

