---

- command: ovs-vsctl show | grep br-int
  register: br_int_exist
  ignore_errors: True
  failed_when: br_int_exist.rc not in [0, 1]

- name: setting openswitch add br-int for neutron-l3
  shell: >
    ovs-vsctl add-br br-int
  ignore_errors: True

- name: install neutron
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
    - "neutron-l3-agent"
    - "neutron-dhcp-agent"
    - "neutron-metadata-agent"
    - "neutron-metering-agent"
    - "neutron-lbaas-agent"
    - "neutron-plugin-openvswitch-agent"

- command: grep FOR_CHK /etc/neutron/neutron.conf
  register: chk_neutron_conf
  ignore_errors: True
  failed_when: chk_neutron_conf.rc not in [0, 1]

- name: setting neutron l3_agent config
  template: >
    src=l3_agent.ini.j2
    dest=/etc/neutron/l3_agent.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network

- name: setting neutron dhcp_agent config
  template: >
    src=dhcp_agent.ini.j2
    dest=/etc/neutron/dhcp_agent.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network

- name: setting dnsmasq mtu config
  template: >
    src=dnsmasq-neutron.conf.j2
    dest=/etc/neutron/dnsmasq-neutron.conf
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network

- name: setting neutron metadata_agent config
  template: >
    src=metadata_agent.ini.j2
    dest=/etc/neutron/metadata_agent.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network

- name: setting neutron metering config
  template: >
    src=metering_agent.ini.j2
    dest=/etc/neutron/metering_agent.ini
    owner=root
    group=root
    mode=0644
    backup=yes
  notify:
    - restart neutron network

- name: setting neutron lbaas_agent config
  template: >
    src=lbaas_agent.ini.j2
    dest=/etc/neutron/lbaas_agent.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network

- name: setting neutron fwaas_agent config
  template: >
    src=fwaas_driver.ini.j2
    dest=/etc/neutron/fwaas_driver.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network

- name: setting neutron ml2 config
  template: >
    src=ml2_conf.ini.j2
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    owner=root
    group=neutron
    mode=0644
    backup=yes
  notify:
    - restart neutron network

- name: setting neutron openvswitch_agent config
  template: >
    src=openvswitch_agent.ini.j2
    dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini
    owner=root
    group=neutron
    mode=0644
    backup=yes
  notify:
    - restart neutron network

- name: setting neutron db sync
  shell: >
    /usr/bin/neutron-db-manage --config-file /etc/neutron/neutron.conf \
                               --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  notify:
    - restart neutron network

