---

- name: install neutron
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
    - "neutron-l3-agent"
    - "neutron-dhcp-agent"
    - "neutron-metadata-agent"
    - "neutron-plugin-openvswitch-agent"

- name: setting neutron config
  template: >
    src=neutron.conf.j2
    dest=/etc/neutron/neutron.conf
    owner=neutron
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-flat"

- name: check nova_tenant_id
  shell: . /home/stack/admin-openrc.sh ; keystone tenant-list | grep service | awk '{print $2}'
  register: nova_tenant_id
  when: network_type == "neutron-flat"

- name: setting neutron config nova_tenant_id
  lineinfile:
    dest=/etc/neutron/neutron.conf
    state=present
    regexp='xxxx'
    line="nova_admin_tenant_id = {{ item }}"
    backup=yes
  with_items: nova_tenant_id.stdout_lines
  when: network_type == "neutron-flat"

- name: setting neutron l3_agent config
  template: >
    src=l3_agent.ini.j2
    dest=/etc/neutron/l3_agent.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-flat"

- name: setting neutron l3_agent config
  template: >
    src=dhcp_agent.ini.j2
    dest=/etc/neutron/dhcp_agent.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-flat"

- name: setting neutron metadata_agent config
  template: >
    src=metadata_agent.ini.j2
    dest=/etc/neutron/metadata_agent.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-flat"

- name: setting neutron ml2 config
  template: >
    src=ml2_conf.ini.j2
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-flat"

