---

- name: Cmmon Settings
  hosts: all
  sudo: true
  roles:
    - { role: common }

- name: NTP Install
  hosts: all
  sudo: true
  roles:
    - { role: ntp }

- name: RabbitMQ Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: rabbitmq }

- name: MySQL Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: mysql }

- name: Memcached Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: memcached }

- name: Keystone Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: keystone_install }

- name: Keystone Settings
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: keystone_settings }

- name: Glance Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: glance }

- name: OpenStack Image Registry
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: glance_image }

- name: Nova Controller Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: nova_control }

- name: Nova Compute Install
  #hosts: openstack_compute
  hosts: all
  sudo: true
  roles:
    - { role: nova_compute }

- name: Horizon Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: horizon }

- name: Cinder Controller Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: cinder_control, when: use_cinder == "use" }

- name: Cinder Volume Install
  #hosts: openstack_volume
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: cinder_volume, when: use_cinder == "use" }

- name: Ceilometer Controller Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: ceilometer_control, when: use_ceilometer == "use" }

- name: Ceilometer Compute Install
  #hosts: openstack_compute
  hosts: all
  sudo: true
  roles:
    - { role: ceilometer_compute, when: use_ceilometer == "use" }

- name: OpenStack Common Settings 
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: openstack_settings }

- name: Neutron Controller Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: neutron_control, when: network_type == "neutron-flat" or network_type == "neutron-l3" }

- name: Neutron Network Install
  #hosts: openstack_network
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: neutron_network, when: network_type == "neutron-flat" or network_type == "neutron-l3" }

- name: Neutron Compute Install
  #hosts: openstack_comptue
  hosts: all
  sudo: true
  roles:
    - { role: neutron_compute, when: network_type == "neutron-flat" or network_type == "neutron-l3" }

- name: OpenStack Neutron Service Restart For Control
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: neutron_restart_ctl, when: network_type == "neutron-flat" or network_type == "neutron-l3" }

- name: OpenStack Neutron Service Restart For Network
  #hosts: openstack_network
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: neutron_restart_network, when: network_type == "neutron-flat" or network_type == "neutron-l3" }

- name: OpenStack Neutron Service Restart For Compute
  #hosts: openstack_compute
  hosts: all
  sudo: true
  roles:
    - { role: neutron_restart_compute, when: network_type == "neutron-flat" or network_type == "neutron-l3" }

- name: OpenStack Network Settings 
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: network_settings }

