---

- name: install Nova
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
   - "nova-api"
   - "nova-cert"
   - "nova-conductor"
   - "nova-consoleauth"
   - "nova-objectstore"
   - "nova-scheduler"
   - "python-novaclient"
   - "nova-spiceproxy"

- name: setting nova config for neutron
  template: >
    src=nova.conf_neutron
    dest=/etc/nova/nova.conf
    owner=nova
    group=nova
    mode=0640
    backup=yes
  notify:
    - restart nova control

- name: nova db sync
  command: /usr/bin/nova-manage db sync
  become: yes
  become_user: nova

