---

- name: create databases
  mysql_db: >
    name=neutron
    state=present
    encoding=utf8

- name: database user create
  mysql_user: >
    name=neutron
    host={{ item }}
    password={{ mysql_neutron_password }}
    priv=neutron.*:ALL
  with_items: 
    - '%'
    - 'localhost'

