---

- name: create users
  keystone:
    command: "ensure_user"
    user_name: "{{ item.name }}"
    project_name: "service"
    password: "{{ item.password }}"
    endpoint: "{{ item.os_url }}"
    token: "{{ admin_token }}"
  with_items: users

- name: is added to the role you create a user
  keystone:
    command: "ensure_user_role"
    user_name: "{{ item.name }}"
    project_name: "service"
    role_name: "admin"
    endpoint: "{{ item.os_url }}"
    token: "{{ admin_token }}"
  with_items: users

- name: create service
  keystone:
    command: "ensure_service"
    service_name: "{{ item.name }}"
    service_type: "{{ item.type }}"
    description: "{{ item.description }}"
    endpoint: "{{ item.os_url }}"
    token: "{{ admin_token }}"
  with_items: services

- name: create endpoints
  keystone:
    command: "ensure_endpoint"
    region_name: "RegionOne"
    service_name: "{{ item.name }}"
    service_type: "{{ item.type }}"
    endpoint_list:
      - url: "{{ item.public_url }}"
        interface: "public"
      - url: "{{ item.internal_url }}"
        interface: "internal"
      - url: "{{ item.admin_url }}"
        interface: "admin"
    endpoint: "{{ item.os_url }}"
    token: "{{ admin_token }}"
  with_items: services

