---

- name: add neutron vhost
  rabbitmq_vhost: 
    name=/neutron
    state=present

- name: add neutron user
  rabbitmq_user:
    user={{ neutron_mq_user }}
    password={{ neutron_mq_password }}
    vhost=/neutron
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    state=present

