---

- name: install neutron
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
   - "neutron-server"
   - "neutron-plugin-ml2"
   - "python-neutronclient"

- name: setting neutron config
  template: >
    src=neutron.conf.j2
    dest=/etc/neutron/neutron.conf
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron control
  when: network_type == "neutron-flat"

- name: check nova_tenant_id
  shell: . /home/stack/admin-openrc.sh ; keystone tenant-list | grep service | awk '{print $2}'
  register: nova_tenant_id
  when: network_type == "neutron-flat"

- name: setting neutron config nova_tenant_id
  lineinfile:
    dest=/etc/neutron/neutron.conf
    state=present
    regexp='xxxx'
    line="nova_admin_tenant_id = {{ item }}"
    backup=yes
  with_items: nova_tenant_id.stdout_lines
  when: network_type == "neutron-flat"

