---

- name: install neutron
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
   - "neutron-server"
   - "neutron-plugin-ml2"
   - "python-neutronclient"
   - "neutron-lbaas-agent"
   - "neutron-metering-agent"

- name: setting neutron server config
  template: >
    src=neutron.conf.j2
    dest=/etc/neutron/neutron.conf
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron control

- name: setting neutron ml2 config
  template: >
    src=ml2_conf.ini.j2
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    owner=root
    group=neutron
    mode=0644
    backup=yes
  notify:
    - restart neutron control

- name: neutron setup
  shell: >
    /usr/bin/neutron-db-manage --config-file /etc/neutron/neutron.conf \
                               --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  become: yes
  become_user: neutron
  notify:
    - restart neutron control

