---

- name: create keypair
  os_keypair:
    cloud: "{{ generic_project01 }}"
    state: "present"
    name:  "{{ keypaire_name }}"
    public_key_file: "{{ operate_user_home }}/.ssh/id_rsa.pub"

- name: delete m1.tiny
  os_nova_flavor:
    cloud=admin
    state="absent"
    name="m1.tiny"

- name: remake m1.tiny
  os_nova_flavor:
    cloud=admin
    state="present"
    name="m1.tiny"
    ram="512"
    vcpus="1"
    disk="0"
    flavorid="1"

#  shell: >
#    . {{ operate_user_home }}/admin-openrc.sh ; nova flavor-create m1.tiny 1 512 0 1
#  ignore_errors: True
#  when: check_m1_tiny.rc != 0

