---

- command: ovs-vsctl show | grep br-int
  register: br_int_exist
  ignore_errors: True
  failed_when: br_int_exist.rc not in [0, 1]

- name: setting openswitch for br-int
  shell: >
    ovs-vsctl add-br br-int
  ignore_errors: True
  when: network_type == "neutron-flat" and br_int_exist.rc == 1

- name: install neutron
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
    - "neutron-common"
    - "neutron-plugin-ml2"
    - "neutron-plugin-openvswitch-agent"
  when: network_type == "neutron-flat"

- name: setting neutron config
  template: >
    src=neutron.conf.j2
    dest=/etc/neutron/neutron.conf
    owner=neutron
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron compute
  when: network_type == "neutron-flat"

- name: check nova_tenant_id
  shell: . /home/stack/admin-openrc.sh ; keystone tenant-list | grep service | awk '{print $2}'
  register: nova_tenant_id
  when: network_type == "neutron-flat"

- name: setting neutron config nova_tenant_id
  lineinfile:
    dest=/etc/neutron/neutron.conf
    state=present
    regexp='xxxx'
    line="nova_admin_tenant_id = {{ item }}"
    backup=yes
  with_items: nova_tenant_id.stdout_lines
  when: network_type == "neutron-flat"

- name: setting neutron ml2 config
  template: >
    src=ml2_conf.ini.j2
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron compute
  when: network_type == "neutron-flat"

