---

- command: ovs-vsctl show | grep br-int
  register: br_int_exist
  ignore_errors: True
  failed_when: br_int_exist.rc not in [0, 1]

- name: setting openswitch add br-int for neutron-flat
  shell: >
    ovs-vsctl add-br br-int
  ignore_errors: True
  when: network_type == "neutron-flat" and br_int_exist.rc == 1

- name: setting openswitch add br-int for neutron-l3
  shell: >
    ovs-vsctl add-br br-int
  ignore_errors: True
  when: network_type == "neutron-l3" and br_int_exist.rc == 1

- name: install neutron
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
    - "neutron-common"
    - "neutron-l3-agent"
    - "neutron-plugin-ml2"
    - "neutron-plugin-openvswitch-agent"
  when: network_type == "neutron-flat" or network_type == "neutron-l3"

- command: grep FOR_CHK /etc/neutron/neutron.conf
  register: chk_neutron_conf
  ignore_errors: True
  failed_when: chk_neutron_conf.rc not in [0, 1]

- name: setting neutron config for neutron flat
  template: >
    src=neutron.conf.j2
    dest=/etc/neutron/neutron.conf
    owner=neutron
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron compute
  when: network_type == "neutron-flat" and chk_neutron_conf.rc == 1

- name: setting neutron config for neutron l3
  template: >
    src=neutron.conf.j2
    dest=/etc/neutron/neutron.conf
    owner=neutron
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron compute
  when: network_type == "neutron-l3" and chk_neutron_conf.rc == 1

- name: setting neutron config for neutron l3
  template: >
    src=ml2_conf.ini_l3.j2
    dest=/etc/neutron/ml2_conf.ini
    owner=neutron
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron compute
  when: network_type == "neutron-l3" and chk_neutron_conf.rc == 1

- name: setting neutron ml2 config for neutron flat
  template: >
    src=ml2_conf.ini.j2
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron compute
  when: network_type == "neutron-flat"

- name: setting neutron ml2 config for neutron l3
  template: >
    src=ml2_conf.ini_l3.j2
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron compute
  when: network_type == "neutron-l3"

- name: setting neutron fwaas_agent config
  template: >
    src=fwaas_driver.ini.j2
    dest=/etc/neutron/fwaas_driver.ini
    owner=root
    group=neutron
    mode=0640
    backup=yes
  notify:
    - restart neutron network
  when: network_type == "neutron-l3"
