- name: restart ceilometer control
  service: name={{ item }} state=restarted
  with_items:
    - "ceilometer-api"
    - "ceilometer-collector"
    - "ceilometer-agent-central"
    - "ceilometer-agent-notification"
    - "ceilometer-alarm-evaluator"
    - "ceilometer-alarm-notifier"

