---

- name: install python-software-properties
  apt: >
    pkg={{ item }}
    state=present
  with_items:
   - python-software-properties
  when: ansible_distribution == 'Ubuntu' and ansible_lsb.release == "14.04"

- name: add repository for liberty
  apt_repository: >
    repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/liberty main'
    state=present
  when: ansible_distribution == 'Ubuntu' and ansible_lsb.release == "14.04"

- name: apt-get update
  apt: update_cache=yes cache_valid_time=3600

- name: apt-get upgrade
  apt: upgrade=yes cache_valid_time=3600

- name: apt-get dist-upgrade
  apt: upgrade=dist cache_valid_time=3600

- name: install openstack related pkgs
  apt: >
    pkg={{ item }}
    state=present
  with_items:
   - gcc
   - python-dev
   - crudini

- name: check pip install
  command: ls -l /usr/local/bin/pip
  register: chk_pip_install
  ignore_errors: True
  failed_when: chk_pip_install.rc not in [0, 1]

- name: install pip
  shell: curl -kL https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python
  when: chk_pip_install.rc == 2

- name: install openstack python modules
  pip:
    name={{ item }}
  with_items:
   - shade
   - python-openstackclient

