---

- name: restart nova-compute
  service: name=nova-compute state=restarted

- name: restart nova-network
  service: name=nova-network state=restarted

- name: reflect setting of kernel
  shell: sysctl -p

- name: restart libvirt-bin
  service: name=libvirt-bin state=restarted
