---

- name: restart neutron compute
  service: name={{ item }} state=restarted
  with_items:
    - "openvswitch-switch"
    - "neutron-plugin-openvswitch-agent"

- name: start nova-compute
  service: name=nova-compute state=started

