---

- name: create neutron flat network create
  shell: >
    . {{ operate_user_home }}/admin-openrc.sh ; neutron net-create 
    --tenant-id $(keystone tenant-list | grep service | awk '{print $2}')
    {{ item.value.name }}
    --shared
    --provider:network_type flat
    --provider:physical_network physnet1
  ignore_errors: True
  with_dict: neutron_flat_networks
  when: network_type == "neutron-flat"

- name: create neutron flat subnet create
  shell: >
    . {{ operate_user_home }}/admin-openrc.sh ; neutron subnet-create 
    --ip-version 4
    --tenant-id $(keystone tenant-list | grep service | awk '{print $2}')
    {{ item.value.name }}
    {{ item.value.sbunet }}
    --allocation-pool start={{ item.value.ip_pool_start }},end={{ item.value.iP_pool_end }}
    --dns_nameservers list=true {{ item.value.dns1 }} {{ item.value.dns2 }}
  ignore_errors: True
  with_dict: neutron_flat_networks
  when: network_type == "neutron-flat"

- name: secgroup settings
  shell: >
    . {{ operate_user_home }}/admin-openrc.sh ; nova secgroup-add-rule
    {{ item.value.name }}
    {{ item.value.protocol }}
    {{ item.value.from_port }}
    {{ item.value.to_port }}
    {{ item.value.cidr }}
  ignore_errors: True
  with_dict: secgroup_rules
  when: network_type == "neutron-flat"

