---

services:
  - name: cinder
    type: volume
    description: "OpenStack Block Storage"
    public_url: http://{{ controller_ext_ip }}:8776/v1/%(tenant_id)s
    internal_url: http://{{controller_int_ip }}:8776/v1/%(tenant_id)s
    admin_url: http://{{controller_int_ip }}:8776/v1/%(tenant_id)s
    os_url: http://{{ controller_int_ip }}:35357/v3
  - name: cinderv2
    type: volumev2
    description: "OpenStack Block Storage"
    public_url: http://{{ controller_ext_ip }}:8776/v2/%(tenant_id)s
    internal_url: http://{{controller_int_ip }}:8776/v2/%(tenant_id)s
    admin_url: http://{{controller_int_ip }}:8776/v2/%(tenant_id)s
    os_url: http://{{ controller_int_ip }}:35357/v3

users:
  - name: cinder
    password: "{{ cinder_keystone_password }}"
    os_url: http://{{ controller_int_ip }}:35357/v3

